@token = 

###

GET http://localhost:3030/api/usuarios
Authorization: Bearer {{token}}

###

POST http://localhost:3030/api/usuarios
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "email": "pingu@igloo.com",
    "password": "5uperClav€",
    "nombre": "pingu",
    "rol": "Usuario"
}

###

POST http://localhost:3030/api/usuarios/clientes
Content-Type: application/json

{
    "email": "cliente@correo.com",
    "password": "Cl13ente?",
    "nombre": "cliente"
}

###

PUT http://localhost:3030/api/usuarios/pingu@igloo.com
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "email": "pingu@igloo.com",
    "password": "5uperClav€",
    "nombre": "sudo pingu",
    "rol": "Administrador"
}

###

DELETE http://localhost:3030/api/usuarios/cliente@correo.com
Authorization: Bearer {{token}}
